# Generated by Django 2.1.1 on 2018-09-26 05:35

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaouser',
            name='context',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
